[features]
seeds = false
skip-lint = false

[programs.localnet]
rpg = "CjkabKt6n2YWfMbxbBprFoso9wYCJNB1FxngrHo4d9gf"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/dr222/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
